# Local development overrides for kamer-pro-chart
ingress:
  enabled: false

backend:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

frontend:
  service:
    type: NodePort
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

postgresql:
  image:
    repository: bitnami/postgresql
    tag: "12.1.6-debian-10-r28"
    pullPolicy: IfNotPresent
  primary:
    persistence:
      enabled: false