{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kamerlink.fullname" . }}-backend-data
  labels:
    {{- include "kamerlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
---
{{- if .Values.backend.uploads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kamerlink.fullname" . }}-backend-uploads
  labels:
    {{- include "kamerlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.backend.uploads.accessMode }}
  {{- if .Values.backend.uploads.storageClass }}
  storageClassName: {{ .Values.backend.uploads.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.uploads.size }}
{{- end }}