apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kamerlink.fullname" . }}-frontend-config
  labels:
    {{- include "kamerlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  VITE_API_URL: "http://{{ include "kamerlink.fullname" . }}-backend:{{ .Values.backend.service.port }}/api"