{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kamerlink.fullname" . }}-postgresql
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}