use actix_web::web;

/// Configure all API routes
pub fn configure_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(crate::aggregate::dashboard_summary)
        .service(crate::aggregate::health_check)
        .service(
            web::scope("/auth")
                .service(kamer_auth::registration_start)
                .service(kamer_auth::registration_complete)
                .service(kamer_auth::authentication_start)
                .service(kamer_auth::authentication_complete)
                .service(kamer_auth::simple_register)
                .service(kamer_auth::simple_login)
                .service(kamer_auth::logout),
        )
        .service(
            web::scope("/roles")
                .service(kamer_admin::get_user_role)
                .service(kamer_admin::set_user_role),
        )
        .service(
            web::scope("/listings")
                .service(kamer_listings::get_all_listings)
                .service(kamer_listings::get_towns)
                .service(kamer_listings::get_host_listings)
                .service(kamer_listings::get_reviews)
                .service(kamer_listings::add_review)
                .service(kamer_listings::create_listing)
                .service(kamer_listings::get_my_listings)
                .service(kamer_listings::get_listing)
                .service(kamer_listings::update_listing)
                .service(kamer_listings::delete_listing)
                .service(kamer_listings::publish_listing)
                .service(kamer_listings::unpublish_listing)
                .service(kamer_listings::add_amenities)
                .service(kamer_listings::sync_photos)
                .service(kamer_listings::add_video),
        )
        .service(
            web::scope("/upload")
                .service(crate::upload::upload_images)
                .service(crate::upload::upload_images_standalone),
        )
        .service(
            web::scope("/messages")
                .service(kamer_messages::create_conversation)
                .service(kamer_messages::get_conversations)
                .service(kamer_messages::get_messages)
                .service(kamer_messages::send_message)
                .service(kamer_messages::get_unread_count)
                .service(kamer_messages::get_message_templates),
        )
        .service(
            web::scope("/account")
                .service(kamer_accounts::get_me)
                .service(kamer_accounts::get_user_by_id)
                .service(kamer_accounts::update_account),
        )
        .service(
            web::scope("/wishlist")
                .service(kamer_wishlist::get_wishlist)
                .service(kamer_wishlist::add_to_wishlist)
                .service(kamer_wishlist::remove_from_wishlist)
                .service(kamer_wishlist::remove_from_wishlist_by_product)
                .service(kamer_wishlist::check_wishlist),
        )
        .service(
            web::scope("/bookings")
                .service(kamer_bookings::create_booking)
                .service(kamer_bookings::get_today_bookings)
                .service(kamer_bookings::get_upcoming_bookings)
                .service(kamer_bookings::get_my_bookings)
                .service(kamer_bookings::approve_booking)
                .service(kamer_bookings::decline_booking)
                .service(kamer_bookings::cancel_booking),
        )
        .service(
            web::scope("/calendar")
                .service(kamer_calendar::get_calendar)
                .service(kamer_calendar::update_calendar_dates)
                .service(kamer_calendar::get_settings)
                .service(kamer_calendar::update_settings),
        )
        .service(web::scope("/reports").service(kamer_admin::create_report))
        .service(crate::translate::translate_text)
        .service(
            web::scope("/admin")
                .service(kamer_admin::get_hosts)
                .service(kamer_admin::delete_host)
                .service(kamer_admin::get_reports),
        );
}
